version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: sandbox
      MONGO_INITDB_ROOT_PASSWORD: deneme12
    ports:
      - 27017:27017
    volumes: 
      - /data/sandbox_mongo_data:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: sandbox
      ME_CONFIG_MONGODB_ADMINPASSWORD: deneme12
      ME_CONFIG_MONGODB_URL: mongodb://sandbox:deneme12@mongo:27017/
